openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de DNS
  description: Documentación de la API de DNS del TP1 de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:

  /domains/{domain_name}:
    get:
      operationId: "api.domains.get_one"
      tags:
        - "Domains"
      summary: "Alumno de la materia"
      description: "Obtiene una ip relacionada a un dominio particular especificando si es o no custom"
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: Nombre del dominio a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"

  /custom-domains:
    get:
      operationId: "api.domains.get"
      tags:
        - "Domains"
      summary: "Colección de dominios personalizados"
      description: "Obtiene la lista de todos los dominios personalizados en el sistema"
      parameters:
        - in: query
          name: q
          required: false
          schema:
            type: string
          description: Nombre en el dominio a buscar
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain_array'
        404:
          description: "Dominio no encontrado"
    post:
      operationId: "api.domains.create"
      tags:
        - "Domains"
      summary: "Alta de un dominio personalizado"
      description: "Crea un nuevo dominio y lo agrega a la lista de dominios personalizados"
      requestBody:
        required: true
        x-body-name: 'dominio'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se creo el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Dominio duplicado"

  /custom-domains/{domain_name}:
    put:
      operationId: "api.domains.edit"
      tags:
        - "Domains"
      summary: "Modificar dominio personalizado"
      description: "modifica un dominio personalizado"
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: Nombre del dominio a obtener
      requestBody:
        required: true
        x-body-name: 'dominio'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        200:
          description: "Se ha modificado el dominio exitosamente"
        404:
          description: "Dominio no encontrado"

    delete:
      operationId: "api.domains.delete"
      tags:
        - "Domains"
      summary: "Borrar dominio personalizado"
      description: "Borra un dominio personalizado"
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: Nombre del dominio a borrar
      responses:
        200:
          description: "Operación de borrado exitosa"
        404:
          description: "Dominio no encontrado"
# Declaración de tipos de datos
components:
  schemas:
    Domain_array:
      type: "object"
      properties:
        items:
          type: "array"
          items:
            $ref: '#/components/schemas/Domain'
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
